### PR TITLE
Fix treatment of no-output ERB tags

### LINKED ISSUE #15: Parsing Error when using no-output erb tags in certain contexts
Thanks for the plugin! I'm trying to get it running on our existing codebase, but I've run into a situation where most of our erb files don't parse. They contain code something similar to:

```erb
OSM = {
<% if something %>
  MATOMO: <%= Settings.matomo.to_json %>,
<% end %>
  MAX_REQUEST_AREA: <%= Settings.max_request_area.to_json %>
}
```

If I understand correctly, both `<% %>` and `<%= %>` tags [get converted into the same placeholder](https://github.com/Splines/eslint-plugin-erb/blob/9c26b3569b00cc0a92f17e8e9b18c7de87e58a15/lib/preprocess.js#L92) - effectively `{}`. However, this leads to the parser error:

```js
OSM = {
{}
  MATOMO: {},
{}
  MAX_REQUEST_AREA: {}
}
```

I can see that replacing the erb-output tags (e.g. `<%= %>`) with `{}` makes sense. But does the same hold true for the non-output tags like `<% %>`? Would it be better to use a different placeholder (e.g. just a comment with the hash etc) for these tags?

```js
OSM = {
/* zero output placeholder comment */
  MATOMO: {},
/* zero output placeholder comment */
  MAX_REQUEST_AREA: {}
}
```

Sorry in advance if I'm overlooking anything here!

### PR DESCRIPTION
**Pull request by Splines**
Fixes #15. We now use the replacement to `{}` only if the ERB tag starts with `<%=`. For all other tags (including `<%` and `<%#`), we replace them by a simple comment, without any actual remaining JS-syntax (i.e. no `{}`).

A respective test was added.

### CODE REVIEW

File: lib/preprocess.js [hunk 1]
```diff
@@ -88,17 +87,24 @@ function replaceTextWithDummy(lintableTextArr, startIndex, length, dummy) {
...
+    return `/* eslint-disable */${text}/* eslint-enable */`;
   }
-  return preprocess(text, filename, dummyString);
+
+  function toDummyString(id, matchText) {
+    if (matchText.startsWith("<%=")) {
+      return wrapInEslintDisable(`{}/* eslint-plugin-erb ${HASH} ${id} */`);
+    }
+    return wrapInEslintDisable(`/* eslint-plugin-erb ${HASH} ${id} */`);
+  }
```
Comment (hlfan) [inline lib/preprocess.js:99]: I'm just gonna leave this idea here, I don't feel like forking this repo today:
```suggestion
  function toDummyString(id, matchText) {
    let replacement = "";
    if (matchText.startsWith("<%=")) replacement = "{}";
    const tagged = `${replacement}/* eslint-plugin-erb ${HASH} ${id} */`;
    const wrapped = `/* eslint-disable */${tagged}/* eslint-enable */`;
    return wrapped;
  }
```
